"""
SuperSploit Investigative Dossier Engine
Performs a professional-grade background check by aggregating public records, 
legal filings, address history, and corporate associations.
Generates a structured 'Investigative Dossier' PDF report.
"""

import sys
import os
import urllib.parse
import datetime
import json
import uuid

# Framework integration
current_dir = os.path.dirname(os.path.abspath(__file__))
framework_root = os.path.abspath(os.path.join(current_dir, "..", ".."))
source_dir = os.path.join(framework_root, "source")

if source_dir not in sys.path:
    sys.path.append(source_dir)

try:
    from core.database import DatabaseManagment
    from core.license_manager import LicenseManager
    has_db = True
except ImportError:
    # Handle standalone execution
    if source_dir not in sys.path: sys.path.append(source_dir)
    try:
        from core.database import DatabaseManagment
        from core.license_manager import LicenseManager
        has_db = True
    except ImportError:
        has_db = False
        class LicenseManager:
            @staticmethod
            def check_pro_status(): return False

try:
    from fpdf import FPDF
    has_pdf = True
except ImportError:
    has_pdf = False

#!#!#!
name: "Investigative Dossier Engine"
description: "Professional background check aggregator. Targets addresses, criminal records, corporate ties, and social footprints."
category: "OSINT"
author: "Donald Ford"
#!#!#!

class DossierReport(FPDF if has_pdf else object):
    """Custom PDF class for professional dossier formatting."""
    def sanitize_text(self, text):
        """Strips non-latin-1 characters to prevent encoding errors."""
        if not isinstance(text, str): return text
        return text.encode('latin-1', 'ignore').decode('latin-1')

    def header(self):
        if not has_pdf: return
        self.set_font('Arial', 'B', 15)
        self.cell(0, 10, 'CONFIDENTIAL INVESTIGATIVE DOSSIER', 0, 1, 'C')
        self.set_font('Arial', 'I', 8)
        self.cell(0, 5, f'Generated by SuperSploit OSINT Suite - {datetime.datetime.now().strftime("%Y-%m-%d %H:%M")}', 0, 1, 'C')
        self.ln(10)

    def chapter_title(self, title):
        title = self.sanitize_text(title)
        self.set_font('Arial', 'B', 12)
        self.set_fill_color(200, 220, 255)
        self.cell(0, 8, title, 0, 1, 'L', 1)
        self.ln(4)

    def chapter_body(self, body):
        body = self.sanitize_text(body)
        self.set_font('Arial', '', 10)
        self.multi_cell(0, 5, body)
        self.ln()

    def add_dork_link(self, label, query):
        url = f"https://www.google.com/search?q={urllib.parse.quote_plus(query)}"
        self.set_font('Arial', 'B', 9)
        self.cell(40, 6, f"{label}: ", 0, 0)
        self.set_font('Arial', '', 9)
        self.set_text_color(0, 0, 255)
        self.cell(0, 6, query, 0, 1, 'L', False, url)
        self.set_text_color(0, 0, 0)

def generate_professional_dorks(name, location=None):
    """Generates a professional-grade OSINT dork map."""
    n = f'"{name}"'
    # Treat "Unknown" as None to avoid it appearing as a literal search term
    if location == "Unknown": location = None
    loc = f'"{location}"' if location else ""
    
    return {
        "📍 ADDRESS & RESIDENCY HISTORY": [
            f'{n} {loc} site:voterrecords.com',
            f'{n} {loc} site:truepeoplesearch.com',
            f'{n} {loc} site:whitepages.com',
            f'{n} {loc} site:thatsthem.com',
            f'{n} {loc} site:fastpeoplesearch.com',
            f'{n} {loc} "address" OR "lives at"'
        ],
        "⚖️ CRIMINAL & LEGAL RECORDS": [
            f'{n} {loc} site:judyrecords.com',
            f'{n} {loc} site:jailbase.com',
            f'{n} {loc} site:mugshots.com OR site:arrests.org',
            f'{n} {loc} intitle:court OR intitle:arrest OR intitle:criminal',
            f'{n} {loc} intext:judgment OR intext:liens OR intext:bankruptcy',
            f'{n} {loc} filetype:pdf "affidavit" OR "indictment"'
        ],
        "💼 CORPORATE & PROFESSIONAL": [
            f'{n} {loc} site:opencorporates.com',
            f'{n} {loc} site:bizapedia.com',
            f'{n} {loc} site:linkedin.com',
            f'{n} {loc} site:zoominfo.com OR site:crunchbase.com',
            f'{n} {loc} site:glassdoor.com "reviews"'
        ],
        "📱 SOCIAL & ALIAS DISCOVERY": [
            f'{n} site:facebook.com OR site:instagram.com OR site:twitter.com',
            f'{n} site:reddit.com OR site:medium.com OR site:quora.com',
            f'{n} site:github.com OR site:gitlab.com OR site:stackoverflow.com',
            f'{n} "handle" OR "alias" OR "username"'
        ],
        "📂 UNSTRUCTURED DATA & LEAKS": [
            f'{n} site:pastebin.com OR site:ghostbin.com',
            f'{n} filetype:pdf OR filetype:xlsx OR filetype:docx',
            f'{n} "password" OR "credential" OR "login"'
        ]
    }

def Start(args=None):
    name = ""
    location = None
    
    if args:
        name = args[0]
        if len(args) > 1: location = args[1]
    elif has_db:
        db = DatabaseManagment.get()
        active_profile = db.get("ACTIVE_PROFILE")
        r_host = db.get("R_HOST", "")

        # 1. Try Active Profile first
        if active_profile:
            profiles = DatabaseManagment.getProfiles()
            if active_profile in profiles:
                p_data = profiles[active_profile]
                name = p_data.get("name", active_profile)
                location = p_data.get("geolocation") or p_data.get("address")
        
        # 2. Try resolving R_HOST to a profile
        if not name and r_host:
            profiles = DatabaseManagment.getProfiles()
            for p_name, p_data in profiles.items():
                if p_data.get("ip") == r_host or p_name == r_host:
                    name = p_data.get("name", p_name)
                    location = p_data.get("geolocation") or p_data.get("address")
                    break
            
            # 3. Fallback to R_HOST itself if it's not a raw IP
            if not name and not r_host.replace('.', '').isdigit():
                name = r_host

    if not name or name.replace('.', '').isdigit():
        print("[-] Error: Target name required (e.g., run \"John Doe\" \"New York\")")
        print("[*] Tip: Use 'set profile <Name>' to link an OSINT profile to your session.")
        return

    print(f"[*] Generating Investigative Dossier for: {name}")
    if location and location != "Unknown": 
        print(f"[*] Target Location Context: {location}")

    dork_map = generate_professional_dorks(name, location)

    # Database Synchronization
    if has_db:
        profile = {
            "name": name,
            "geolocation": location or "Unknown",
            "last_audit": datetime.datetime.now().strftime("%Y-%m-%d"),
            "category": "High Value Target"
        }
        DatabaseManagment.addProfile(profile)
        print("[*] Target persona enriched in profiles database.")

    # PDF Generation (Pro Feature)
    if has_pdf:
        if not LicenseManager.check_pro_status():
            print("[*] Skipping Professional Dossier PDF generation (SuperSploit Pro feature).")
        else:
            try:
                pdf = DossierReport()
                pdf.add_page()
                
                pdf.chapter_title("1. TARGET SUMMARY")
                summary = f"Subject Name: {name}\nPrimary Location: {location or 'Not Specified'}\n"
                summary += "Intelligence Level: Multi-Vector Analysis\n"
                summary += f"Report ID: {uuid.uuid4().hex[:8].upper()}"
                pdf.chapter_body(summary)

                for category, dorks in dork_map.items():
                    pdf.chapter_title(category)
                    for d in dorks:
                        pdf.add_dork_link(category.split()[-1], d)
                    pdf.ln(4)

                pdf.chapter_title("6. INVESTIGATIVE NOTES")
                pdf.chapter_body("Data aggregated from public repositories. No active intrusion was performed. All links point to publicly accessible records or search indices.")

                # Save to loot
                install = DatabaseManagment.getInstall() if has_db else "."
                report_dir = os.path.join(install, ".data", ".loot", "reports")
                os.makedirs(report_dir, exist_ok=True)
                filename = f"Dossier_{name.replace(' ', '_')}.pdf"
                report_path = os.path.join(report_dir, filename)
                pdf.output(report_path)
                print(f"[+] Investigative Dossier Exported: {report_path}")
                
            except Exception as e:
                print(f"[-] PDF Export Error: {e}")

    # CLI Output
    print(f"\n[*] Dossier Structure for {name}:")
    for category, dorks in dork_map.items():
        print(f"\n{category}")
        for d in dorks:
            print(f"  - {d}")

if __name__ == "__main__":
    Start(sys.argv[1:])
