import sys
import os
import urllib.parse
import datetime
import uuid

# Dynamically append the framework's source directory to sys.path
# so the module can interact with the core framework when loaded.
_scanner_dir = os.path.dirname(os.path.abspath(__file__))
_framework_root = os.path.abspath(os.path.join(_scanner_dir, "..", ".."))
_source_dir = os.path.join(_framework_root, "source")
if _source_dir not in sys.path:
    sys.path.append(_source_dir)

try:
    from core.database import DatabaseManagment
    from core.license_manager import LicenseManager
    has_db = True
except ImportError:
    # Handle standalone execution
    if _source_dir not in sys.path: sys.path.append(_source_dir)
    try:
        from core.database import DatabaseManagment
        from core.license_manager import LicenseManager
        has_db = True
    except ImportError:
        has_db = False
        class LicenseManager:
            @staticmethod
            def check_pro_status(): return False

try:
    from fpdf import FPDF
    has_pdf = True
except ImportError:
    has_pdf = False

#!#!#!
name: "Native Email OSINT"
description: "Identify social media profiles, leaked credentials, and mentions across public data repositories via email."
category: "OSINT"
author: "Donald Ford"
keywords: '["email", "osint", "recon", "leaks", "dorking"]'
#!#!#!

class DossierReport(FPDF if has_pdf else object):
    """Custom PDF class for professional dossier formatting."""
    def sanitize_text(self, text):
        """Strips non-latin-1 characters to prevent encoding errors."""
        if not isinstance(text, str): return text
        return text.encode('latin-1', 'ignore').decode('latin-1')

    def header(self):
        if not has_pdf: return
        self.set_font('Arial', 'B', 15)
        self.cell(0, 10, 'CONFIDENTIAL OSINT REPORT', 0, 1, 'C')
        self.set_font('Arial', 'I', 8)
        self.cell(0, 5, f'Generated by SuperSploit OSINT Suite - {datetime.datetime.now().strftime("%Y-%m-%d %H:%M")}', 0, 1, 'C')
        self.ln(10)

    def chapter_title(self, title):
        title = self.sanitize_text(title)
        self.set_font('Arial', 'B', 12)
        self.set_fill_color(200, 220, 255)
        self.cell(0, 8, title, 0, 1, 'L', 1)
        self.ln(4)

    def chapter_body(self, body):
        body = self.sanitize_text(body)
        self.set_font('Arial', '', 10)
        self.multi_cell(0, 5, body)
        self.ln()

    def add_dork_link(self, label, query):
        url = f"https://www.google.com/search?q={urllib.parse.quote_plus(query)}"
        self.set_font('Arial', 'B', 9)
        self.cell(40, 6, f"{label}: ", 0, 0)
        self.set_font('Arial', '', 9)
        self.set_text_color(0, 0, 255)
        self.cell(0, 6, query, 0, 1, 'L', False, url)
        self.set_text_color(0, 0, 0)

def google_dork(email):
    """
    Generates categorized Google Dork URLs specifically targeted at email address discovery.
    """
    return {
        "🔍 PRIMARY AGGREGATORS": [
            f'"{email}"',
            f'intitle:"{email}"',
            f'"{email}" site:whitepages.com',
            f'"{email}" site:spokeo.com',
            f'"{email}" site:truepeoplesearch.com',
            f'"{email}" site:peekyou.com',
            f'"{email}" site:voterrecords.com',
            f'"{email}" site:thatsthem.com'
        ],
        "⚖️ LEGAL & CRIMINAL": [
            f'"{email}" intitle:court OR intitle:arrest OR intitle:criminal OR intitle:mugshot',
            f'"{email}" filetype:pdf (intext:judgment OR intext:liens OR intext:bankruptcy OR intext:divorce)',
            f'"{email}" site:judyrecords.com',
            f'"{email}" site:jailbase.com'
        ],
        "💼 SOCIAL & PROFESSIONAL": [
            f'"{email}" site:linkedin.com',
            f'"{email}" site:facebook.com OR site:instagram.com OR site:x.com OR site:tiktok.com',
            f'"{email}" site:github.com OR site:gitlab.com OR site:stackoverflow.com',
            f'"{email}" site:crunchbase.com OR site:zoominfo.com OR site:rocketreach.co',
            f'"{email}" site:about.me OR site:linktr.ee OR site:behance.net'
        ],
        "📂 DOCUMENT LEAKS & PASTES": [
            f'"{email}" (site:pastebin.com OR site:controlc.com OR site:scribd.com OR site:slideshare.net)',
            f'"{email}" filetype:xls OR filetype:xlsx OR filetype:csv "intext:email" OR "intext:phone"',
            f'"{email}" filetype:pdf OR filetype:xlsx OR filetype:docx',
            f'"{email}" ext:txt OR ext:log OR ext:sql OR ext:env',
            f'"{email}" intext:"password" OR intext:"pwd" OR intext:"login"'
        ],
        "🌐 PUBLIC DIRECTORIES": [
            f'"{email}" site:leak-lookup.com OR site:breachdirectory.org OR site:intelx.io',
            f'inurl:contact "{email}"',
            f'inurl:staff OR inurl:employees "{email}"'
        ]
    }

def Start(args=None):
    """
    Main entry point for the Email OSINT module.
    """
    email_input = ""
    if args:
        email_input = args[0]
    elif DatabaseManagment:
        db = DatabaseManagment.get()
        email_input = db.get("R_HOST", "")

    # Handle cases where R_HOST is a list
    if isinstance(email_input, list) and email_input:
        email_input = email_input[0]

    # Sanitize input
    email_input = str(email_input).strip()

    if not email_input or "@" not in email_input:
        print("[-] Error: A valid email address is required.")
        print("[*] Usage: set target <user@example.com>  OR  run <email>")
        return

    print(f"[*] Initiating OSINT analysis for email: {email_input}\n")

    try:
        # 1. Verification Logic
        user_part, domain_part = email_input.split('@')
        
        print(f"[+] Initial Analysis")
        print(f"    - Target User:   {user_part}")
        print(f"    - Domain:        {domain_part}")
        
        dork_map = google_dork(email_input)

        # PDF Generation (Pro Feature)
        if has_pdf:
            if not LicenseManager.check_pro_status():
                print("[*] Skipping OSINT Report PDF generation (SuperSploit Pro feature).")
            else:
                try:
                    pdf = DossierReport()
                    pdf.add_page()
                    
                    pdf.chapter_title("1. TARGET INFORMATION")
                    summary = f"Email Address: {email_input}\n"
                    summary += f"Username: {user_part}\n"
                    summary += f"Domain: {domain_part}\n"
                    summary += f"Report ID: {uuid.uuid4().hex[:8].upper()}"
                    pdf.chapter_body(summary)

                    for category, dorks in dork_map.items():
                        pdf.chapter_title(category)
                        for d in dorks:
                            pdf.add_dork_link(category.split()[-1], d)
                        pdf.ln(4)

                    pdf.chapter_title("6. INVESTIGATIVE NOTES")
                    pdf.chapter_body("Data aggregated from public repositories. No active intrusion was performed. All links point to publicly accessible records or search indices.")

                    # Save to loot
                    install = DatabaseManagment.getInstall() if has_db else "."
                    report_dir = os.path.join(install, ".data", ".loot", "reports")
                    os.makedirs(report_dir, exist_ok=True)
                    filename = f"Email_OSINT_{email_input.replace('@', '_at_')}.pdf"
                    report_path = os.path.join(report_dir, filename)
                    pdf.output(report_path)
                    print(f"[+] OSINT Report Exported: {report_path}")
                    
                except Exception as e:
                    print(f"[-] PDF Export Error: {e}")

        # CLI Output
        print(f"\n[*] Generating Email Footprints (Copy into browser):")
        for category, dorks in dork_map.items():
            print(f"\n{category}")
            for d in dorks:
                query = urllib.parse.quote_plus(d)
                print(f"    - {d}")
                print(f"      URL: https://www.google.com/search?q={query}")

    except Exception as e:
        print(f"[-] Analysis Error: {e}")

if __name__ == "__main__":
    Start(sys.argv[1:])