import sys
import os
import urllib.parse
import threading

# Dynamically append the framework's source directory to sys.path
# so the module can interact with the core framework when loaded.
_scanner_dir = os.path.dirname(os.path.abspath(__file__))
_framework_root = os.path.abspath(os.path.join(_scanner_dir, "..", ".."))
_source_dir = os.path.join(_framework_root, "source")
if _source_dir not in sys.path:
    sys.path.append(_source_dir)

try:
    from core.database import DatabaseManagment
    from core.license_manager import LicenseManager
    has_db = True
except ImportError:
    has_db = False
    class LicenseManager:
        @staticmethod
        def check_pro_status(): return False

try:
    from fpdf import FPDF
    has_pdf = True
except ImportError:
    has_pdf = False

try:
    from .background_check import ProfileDB, PersonProfile
except ImportError:
    ProfileDB = None

class DossierReport(FPDF if has_pdf else object):
    """Custom PDF class for professional dossier formatting."""
    def sanitize_text(self, text):
        """Strips non-latin-1 characters to prevent encoding errors."""
        if not isinstance(text, str): return text
        return text.encode('latin-1', 'ignore').decode('latin-1')

    def header(self):
        if not has_pdf: return
        self.set_font('Arial', 'B', 15)
        self.cell(0, 10, 'PHONE OSINT REPORT', 0, 1, 'C')
        self.set_font('Arial', 'I', 8)
        self.cell(0, 5, f'Generated by SuperSploit OSINT Suite', 0, 1, 'C')
        self.ln(10)

    def chapter_title(self, title):
        title = self.sanitize_text(title)
        self.set_font('Arial', 'B', 12)
        self.set_fill_color(200, 220, 255)
        self.cell(0, 8, title, 0, 1, 'L', 1)
        self.ln(4)

    def chapter_body(self, body):
        body = self.sanitize_text(body)
        self.set_font('Arial', '', 10)
        self.multi_cell(0, 5, body)
        self.ln()

    def add_dork_link(self, label, query):
        url = f"https://www.google.com/search?q={urllib.parse.quote_plus(query)}"
        self.set_font('Arial', 'B', 9)
        self.cell(40, 6, f"{label}: ", 0, 0)
        self.set_font('Arial', '', 9)
        self.set_text_color(0, 0, 255)
        self.cell(0, 6, query, 0, 1, 'L', False, url)
        self.set_text_color(0, 0, 0)

#!#!#!
name: "Native Phone OSINT"
description: "Advanced phone number information gathering. Replicates phoneinfoga capabilities natively using Python."
category: "OSINT"
author: "Donald Ford"
keywords: '["phone", "osint", "recon", "dorking"]'
#!#!#!

def google_dork(phone_number):
    """
    Generates categorized Google Dork URLs to find the phone number in various formats.
    """
    return {
        "🔍 PRIMARY AGGREGATORS": [
            f'"{phone_number}"',
            f'"{phone_number}" site:whitepages.com',
            f'"{phone_number}" site:spokeo.com',
            f'"{phone_number}" site:truepeoplesearch.com',
            f'"{phone_number}" site:peekyou.com',
            f'intitle:"index of" "{phone_number}"',
            f'inurl:contact "{phone_number}"'
        ],
        "⚖️ LEGAL & CRIMINAL": [
            f'"{phone_number}" intitle:court OR intitle:arrest OR intitle:criminal',
            f'"{phone_number}" filetype:pdf (intext:judgment OR intext:liens OR intext:bankruptcy)'
        ],
        "💼 SOCIAL & PROFESSIONAL": [
            f'"{phone_number}" site:linkedin.com',
            f'"{phone_number}" site:facebook.com OR site:instagram.com OR site:x.com OR site:tiktok.com',
            f'"{phone_number}" site:github.com OR site:gitlab.com OR site:stackoverflow.com',
            f'"{phone_number}" site:crunchbase.com OR site:angel.co',
            f'inurl:staff OR inurl:employees "{phone_number}"'
        ],
        "📂 DOCUMENT LEAKS & PASTES": [
            f'"{phone_number}" (site:pastebin.com OR site:ghostbin.com OR site:controlc.com OR site:hastebin.com)',
            f'"{phone_number}" filetype:pdf OR filetype:xlsx OR filetype:docx',
            f'"{phone_number}" ext:txt OR ext:log OR ext:sql OR ext:env',
            f'intext:"{phone_number}" (inurl:admin OR inurl:setup)'
        ]
    }

def _run_internal(args=None):
    """Internal execution logic."""
    try:
        import phonenumbers
        from phonenumbers import carrier, geocoder, timezone
    except ImportError:
        print("[-] Error: 'phonenumbers' library is required for native replication.")
        print("[*] Install it via: pip install phonenumbers")
        return

    # Resolve Target Phone Number (Argument > Database)
    phone_input = ""
    if args:
        phone_input = args[0]
    elif has_db:
        db = DatabaseManagment.get()
        phone_input = db.get("R_HOST", "")

    # Handle cases where R_HOST is a list
    if isinstance(phone_input, list) and phone_input:
        # Take the first element as the primary phone number
        phone_input = phone_input[0]

    # Ensure phone_input is a string and stripped of whitespace
    phone_input = str(phone_input).strip()

    if not phone_input:
        print("[-] No phone number target found.")
        print("[*] Usage: set target <+14155552671>  OR  run <number>")
        return

    print(f"[*] Initiating OSINT analysis for: {phone_input}\n")

    try:
        # 1. Parsing & Validation with Region Fallback
        if not phone_input.startswith('+'):
            # If no '+' is found, attempt to parse as a US number by default
            parsed_number = phonenumbers.parse(phone_input, "US")
        else:
            parsed_number = phonenumbers.parse(phone_input, None)

        if not phonenumbers.is_valid_number(parsed_number):
            print("[!] Warning: This number does not appear to be valid according to international standards.")

        # 2. Local Metadata Discovery (No API required)
        fmt_international = phonenumbers.format_number(parsed_number, phonenumbers.PhoneNumberFormat.INTERNATIONAL)
        fmt_e164 = phonenumbers.format_number(parsed_number, phonenumbers.PhoneNumberFormat.E164)
        country = geocoder.description_for_number(parsed_number, "en")
        carrier_name = carrier.name_for_number(parsed_number, "en")
        time_zones = timezone.time_zones_for_number(parsed_number)

        print(f"[+] Local Metadata Discovery")
        print(f"    - International: {fmt_international}")
        print(f"    - E164 Format:   {fmt_e164}")
        print(f"    - Region:        {country}")
        print(f"    - Carrier:       {carrier_name if carrier_name else 'Unknown/Virtual'}")
        print(f"    - Timezone(s):   {', '.join(time_zones)}")

        # PDF Generation (Pro Feature)
        if has_pdf:
            if not LicenseManager.check_pro_status():
                print("\n[*] Skipping Phone OSINT Report PDF generation (SuperSploit Pro feature).")
            else:
                try:
                    pdf = DossierReport()
                    pdf.add_page()
                    
                    pdf.chapter_title("1. TARGET METADATA")
                    summary = f"Phone Number (Intl): {fmt_international}\n"
                    summary += f"Phone Number (E164): {fmt_e164}\n"
                    summary += f"Region: {country}\n"
                    summary += f"Carrier: {carrier_name or 'Unknown'}\n"
                    summary += f"Timezone(s): {', '.join(time_zones)}\n"
                    pdf.chapter_body(summary)

                    dork_map = google_dork(fmt_e164)
                    for category, dorks in dork_map.items():
                        pdf.chapter_title(category)
                        for d in dorks:
                            pdf.add_dork_link(category.split()[-1], d)
                        pdf.ln(4)

                    # Save to loot
                    install = DatabaseManagment.getInstall() if has_db else "."
                    report_dir = os.path.join(install, ".data", ".loot", "reports")
                    os.makedirs(report_dir, exist_ok=True)
                    filename = f"Phone_OSINT_{fmt_e164.replace('+', '')}.pdf"
                    report_path = os.path.join(report_dir, filename)
                    pdf.output(report_path)
                    print(f"\n[+] Phone OSINT Report Exported: {report_path}")
                    
                except Exception as e:
                    print(f"\n[-] PDF Export Error: {e}")

        # 3. Search Engine Footprint (Dorking)
        print(f"\n[*] Generating Google Dorking Footprints (Copy into browser):")
        dork_map = google_dork(fmt_e164)
        for category, dorks in dork_map.items():
            print(f"\n{category}")
            for d in dorks:
                query = urllib.parse.quote_plus(d)
                print(f"    - {d}")
                print(f"      URL: https://www.google.com/search?q={query}")

    except Exception as e:
        print(f"[-] Analysis Error: {e}")

def Start(args=None):
    """
    Main entry point. Replicates the PhoneInfoGa 'scan' routine.
    Wraps execution in a thread with timeout to prevent hanging.
    """
    t = threading.Thread(target=_run_internal, args=(args,))
    t.start()
    t.join(timeout=10) # 10 second timeout for OSINT module
    if t.is_alive():
        print("[-] Error: Module execution timed out.")

if __name__ == "__main__":
    Start(sys.argv[1:])